# mixi Check plugin
# Release 0.9 (Sep 10, 2010)
# 
# Copyright(c) mixi, inc.
#   author: akihiro.tsukui@mixi.co.jp

name: mixi Check Plugin
id: mixiCheck
description: mixi Check Plugin for Movable Type
author_name: akihiro tsukui (mixi, inc.)
author_link: http://alpha.mixi.co.jp/blog/?author=36
doc_link: ../../../plugins/mixiCheck/readme.ja.html
version: 0.9
l10n_class: mixiCheck::L10N

applications:
    cms:
        menus:
            settings:mixi_check:
                label: mixi Check Settings
                view:
                    - website
                    - blog
                mode: cfg_mixi_check
                order: 800
        methods:
            cfg_mixi_check: mixiCheck::cfg_mixi_check
            save_settings: mixiCheck::save_settings

tags:
    function:
        mixiCheckHeader: $mixiCheck::mixiCheck::_hdlr_mixi_check_header
        mixiCheckButton: $mixiCheck::mixiCheck::_hdlr_mixi_check_button
        mixiCheckButtonMB: $mixiCheck::mixiCheck::_hdlr_mixi_check_button_mb
